[package]
name = "rango-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
rango-core = { path = "../rango-core" }
rango-derive = { path = "../rango-derive" }
rango-postgres = { path = "../rango-postgres" }
rango-sqlite = { path = "../rango-sqlite" }
criterion = { version = "0.5", features = ["async_tokio"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
sqlx = { version = "0.8", features = ["sqlite", "postgres", "runtime-tokio-native-tls"] }

[[bench]]
name = "sqlite"
harness = false

[[bench]]
name = "postgres"
harness = false
